### PR TITLE
[UNDER REVIEW] - VR View

### PR DESCRIPTION
**Pull request by ZealRa**
Working on adding a VR view where you can navigate with your keyboard

### CODE REVIEW

**Comment by ZealRa** [comment]
In my last commit, I made the VR function in a separate component, and we can see items appearing:
- nodes, with colors corresponding to the types, but no text
- links, but they're in 2D, not linking nodes between them.
Let's keep looking into this !

**Comment by ZealRa** [comment]
Added the Fly Controls feature on the 3D mode. The VR mode will be improved later, as the 3D is what we were looking for.

**Comment by MacDuPain** [comment]
It is now possible to move with the keyboard in the 3D view. 
The VR view is now working but still needs some improvements as the atom's labels aren't displayed unless you hover your cursor over it.

**Review by MacDuPain — APPROVED** [review]
Code seems fine, the features have been tested locally without any issue on my end.

**Pull request merged**
